# Generated by Django 6.0.6 on 2026-06-21 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('date', models.DateTimeField(verbose_name='活動時間')),
                ('capacity', models.PositiveIntegerField(verbose_name='名額上限')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='已報名人數')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已刪除')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('attended', models.BooleanField(default=False, verbose_name='是否出席')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='報名者')),
            ],
            options={
                'verbose_name': '報名紀錄',
                'verbose_name_plural': '報名紀錄',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
