# Generated by Django 6.0.6 on 2026-06-28 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('school_year', models.PositiveIntegerField(default=113, verbose_name='學年度')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='年度')),
                ('semester', models.IntegerField(choices=[(1, '上學期'), (2, '下學期')], default=1, verbose_name='學期')),
                ('date', models.DateTimeField(verbose_name='活動開始時間')),
                ('end_time', models.DateTimeField(null=True, verbose_name='活動結束時間')),
                ('location', models.CharField(default='', max_length=200, verbose_name='地點')),
                ('organizer', models.CharField(blank=True, default='', max_length=200, verbose_name='主辦單位')),
                ('target_audience', models.CharField(choices=[('不限', '不限'), ('教職員', '教職員'), ('學生', '學生')], default='不限', max_length=200, verbose_name='參加對象')),
                ('registration_start_time', models.DateTimeField(null=True, verbose_name='報名開始時間')),
                ('registration_end_time', models.DateTimeField(null=True, verbose_name='報名結束時間')),
                ('capacity', models.PositiveIntegerField(verbose_name='名額上限')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='已報名人數')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已刪除')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動',
            },
        ),
        migrations.CreateModel(
            name='DeletedEvent',
            fields=[
            ],
            options={
                'verbose_name': '資源回收桶 (已刪除活動)',
                'verbose_name_plural': '資源回收桶 (已刪除活動)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='聯絡信箱')),
                ('check_in_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='簽到專屬ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('attended', models.BooleanField(default=False, verbose_name='是否出席')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='活動')),
            ],
            options={
                'verbose_name': '報名紀錄',
                'verbose_name_plural': '報名紀錄',
                'unique_together': {('event', 'email')},
            },
        ),
    ]
