# Generated by Django 6.0.6 on 2026-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEvent',
            fields=[
            ],
            options={
                'verbose_name': '資源回收桶 (已刪除活動)',
                'verbose_name_plural': '資源回收桶 (已刪除活動)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='school_year',
            field=models.PositiveIntegerField(default=113, help_text='例如：113', verbose_name='學年度'),
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.IntegerField(choices=[(1, '上學期'), (2, '下學期')], default=1, verbose_name='學期'),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='例如：2026', verbose_name='年度'),
        ),
    ]
