# Generated by Django 6.0.6 on 2026-06-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.PositiveIntegerField(help_text='例如：113', verbose_name='學年度')),
                ('year', models.PositiveIntegerField(default=2026, help_text='例如：2026', verbose_name='年度')),
                ('semester', models.IntegerField(choices=[(1, '上學期'), (2, '下學期')], verbose_name='學期')),
                ('summary', models.TextField(verbose_name='活動成果摘要')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='records/images/', verbose_name='活動首圖/照片')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='records/attachments/', verbose_name='附件檔案')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公開展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已刪除')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='events.event', verbose_name='對應活動')),
            ],
            options={
                'verbose_name': '歷年紀錄',
                'verbose_name_plural': '歷年紀錄',
            },
        ),
    ]
