# Generated by Django 6.0.6 on 2026-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='例如：2026', verbose_name='年度'),
        ),
    ]
